import {demoData} from './data.mjs';import {LocalScheduleRepository} from './repository.mjs';import {daysInMonth,calculateGuardPayroll,calculatePayrollSummary,assessWorkload,canEditSchedule} from './domain.mjs';import {buildWorkbookData,downloadXlsx} from './export.mjs';
const $=s=>document.querySelector(s), repo=new LocalScheduleRepository();let selected='g1',hours=12,state;
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function newState(){return{month:$('#month').value,status:'DRAFT',assignments:[],bonuses:{},excludedGuardIds:[],rateAmount:7500}}function load(){state=repo.load($('#month').value)||newState();state.rateAmount=Number(state.rateAmount)||7500;state.excludedGuardIds=state.excludedGuardIds||[];render()}
function fillSelect(el,items){el.innerHTML=items.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
function object(){return demoData.legalEntities.find(x=>x.id===$('#legal').value).objects.find(x=>x.id===$('#object').value)}
function syncFilters(){const le=demoData.legalEntities.find(x=>x.id===$('#legal').value);fillSelect($('#object'),le.objects);syncObject()}
function syncObject(){const o=object();fillSelect($('#post'),o.posts);$('#inspection').textContent=o.inspection;renderGrid()}
function renderGuards(){const q=$('#guard-search').value.toLowerCase();$('#guards').innerHTML=demoData.guards.filter(g=>g.name.toLowerCase().includes(q)).map(g=>`<div class="guard ${g.id===selected?'active':''}" draggable="true" data-id="${g.id}" title="Перетащите на день графика"><b>${g.name}</b><small>${g.engagement} · ${g.rank}</small></div>`).join('');document.querySelectorAll('.guard').forEach(x=>{x.onclick=()=>{selected=x.dataset.id;render()};x.ondragstart=e=>{selected=x.dataset.id;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',x.dataset.id)}})}
function renderGrid(){if(!state)return;const [y,m]=state.month.split('-').map(Number),days=daysInMonth(y,m);$('#schedule-grid').style.setProperty('--days',days);let h='<div class="cell head name">Сотрудник</div>';for(let d=1;d<=days;d++)h+=`<div class="cell head">${d}</div>`;for(const g of demoData.guards.filter(g=>!state.excludedGuardIds.includes(g.id))){h+=`<div class="cell name"><span>${g.name.split(' ').slice(0,2).join(' ')}</span><button class="remove-guard" data-remove="${g.id}" title="Удалить сотрудника из графика">×</button></div>`;for(let d=1;d<=days;d++){const a=state.assignments.find(x=>x.guardId===g.id&&x.day===d),cl=a?.hours===0?'vacation':a?`filled shift-${a.hours}`:'';h+=`<div class="cell slot ${cl}" data-g="${g.id}" data-d="${d}">${a?a.hours===0?'ОТП':a.hours:''}</div>`}}$('#schedule-grid').innerHTML=h;document.querySelectorAll('.remove-guard').forEach(b=>b.onclick=e=>{e.stopPropagation();removeGuard(b.dataset.remove)});document.querySelectorAll('.slot').forEach(c=>{c.onclick=()=>toggle(c.dataset.g,Number(c.dataset.d));c.ondragover=e=>{e.preventDefault();c.classList.add('dragover')};c.ondragleave=()=>c.classList.remove('dragover');c.ondrop=e=>{e.preventDefault();c.classList.remove('dragover');const guardId=e.dataTransfer.getData('text/plain');assign(guardId,Number(c.dataset.d))}})}
function removeGuard(id){if(!canEditSchedule(state))return;const count=state.assignments.filter(x=>x.guardId===id).length;if(confirm(`Удалить сотрудника из графика${count?` и удалить его смены (${count})`:''}?`)){state.assignments=state.assignments.filter(x=>x.guardId!==id);if(!state.excludedGuardIds.includes(id))state.excludedGuardIds.push(id);repo.save(state);render()}}
function assign(g,d){if(!g||!canEditSchedule(state))return;state.excludedGuardIds=state.excludedGuardIds.filter(id=>id!==g);const i=state.assignments.findIndex(x=>x.guardId===g&&x.day===d);if(i>=0)state.assignments.splice(i,1);const current=state.assignments.filter(x=>x.guardId===g);if(assessWorkload([...current,{hours}]).level==='HIGH'&&!confirm('Риск усталости: высокая нагрузка. Подтвердить назначение?'))return;state.assignments.push({guardId:g,day:d,hours,post:$('#post').selectedOptions[0].text});selected=g;repo.save(state);render()}
function toggle(g,d){if(!canEditSchedule(state))return;const i=state.assignments.findIndex(x=>x.guardId===g&&x.day===d);if(i>=0)state.assignments.splice(i,1);else{const current=state.assignments.filter(x=>x.guardId===g);if(assessWorkload([...current,{hours}]).level==='HIGH'&&!confirm('Риск усталости: высокая нагрузка. Подтвердить назначение?'))return;state.assignments.push({guardId:g,day:d,hours,post:$('#post').selectedOptions[0].text})}repo.save(state);render()}
function renderCard(){const g=demoData.guards.find(x=>x.id===selected),items=state.assignments.filter(x=>x.guardId===selected),risk=assessWorkload(items),b=state.bonuses[selected]||{amount:0,reason:''},rate={mode:'SHIFT',amount:state.rateAmount,version:demoData.rates.version},summary=calculatePayrollSummary(demoData.guards,state.assignments,rate,state.bonuses,object().budget);$('#guard-card').innerHTML=`<div><span class="eyebrow">КАРТОЧКА ОХРАННИКА</span><h2>${g.name}</h2><div>${g.note}</div></div><div class="metric">Статус<b>${g.status}</b><br>${g.engagement}</div><div class="metric">Допуски<b>${g.rank}</b><br>УЧО: ${g.license}</div><div class="metric">Контакты<b>${g.phone}</b><br>Стаж: ${g.experience}</div><div class="metric">Назначение<b>${object().name}</b><br>${$('#post').selectedOptions[0].text}</div>`;$('#risk-box').className=risk.level==='HIGH'?'risk-high':'risk-ok';$('#risk-box').innerHTML=`<b>${risk.level==='OK'?'Нагрузка в норме':'Требует внимания'}</b><br>${risk.hours} ч · ${risk.reasons.join(', ')||'критических рисков нет'}`;$('#pay-name').textContent=`Премия: ${g.name}`;$('#budget-value').textContent=money(summary.budget);$('#payroll-total').textContent=money(summary.total);$('#budget-alert').className=summary.overBudget?'budget-alert over':'budget-alert ok';$('#budget-alert').textContent=summary.overBudget?`Вы не уложились в бюджет объекта: превышение ${money(summary.difference)}`:`В бюджете остаётся ${money(-summary.difference)}`;$('#payroll-table tbody').innerHTML=summary.rows.map(row=>`<tr class="${row.guard.id===selected?'selected':''}"><td>${row.guard.name}</td><td>${row.shifts}</td><td>${row.hours}</td><td>${money(state.rateAmount)}</td><td>${money(row.bonus)}</td><td><b>${money(row.total)}</b></td></tr>`).join('');$('#bonus').value=b.amount;$('#bonus-reason').value=b.reason;$('#schedule-title').textContent=`${object().name} · ${state.month}`;$('#status-badge').textContent=state.status==='APPROVED'?'Утверждён':'Черновик';$('#approve-btn').disabled=!canEditSchedule(state);$('#export-btn').disabled=state.status!=='APPROVED';document.querySelectorAll('.rate').forEach(x=>x.classList.toggle('active',Number(x.dataset.rate)===state.rateAmount))}
function render(){renderGuards();renderGrid();renderCard()}
$('#login-form').onsubmit=e=>{e.preventDefault();if($('#password').value==='KIRASA'){$('#login').hidden=true;$('#app').hidden=false}else $('#login-error').textContent='Неверный пароль. Проверьте раскладку и повторите.'};fillSelect($('#legal'),demoData.legalEntities);fillSelect($('#template'),demoData.templates);syncFilters();$('#legal').onchange=syncFilters;$('#object').onchange=syncObject;$('#post').onchange=render;$('#month').onchange=load;$('#guard-search').oninput=renderGuards;document.querySelectorAll('.shift').forEach(b=>b.onclick=()=>{document.querySelectorAll('.shift').forEach(x=>x.classList.remove('active'));b.classList.add('active');hours=Number(b.dataset.hours)});document.querySelectorAll('.rate').forEach(b=>b.onclick=()=>{state.rateAmount=Number(b.dataset.rate);$('#custom-rate').value='';repo.save(state);renderCard()});$('#custom-rate').oninput=()=>{const value=Number($('#custom-rate').value);if(value>0){state.rateAmount=value;repo.save(state);renderCard()}};$('#bonus').oninput=$('#bonus-reason').oninput=()=>{const amount=Number($('#bonus').value)||0,reason=$('#bonus-reason').value;if(amount&&!reason)return;state.bonuses[selected]={amount,reason};repo.save(state);renderCard()};$('#approve-btn').onclick=()=>{if(Object.values(state.bonuses).some(x=>x.amount&&!x.reason))return alert('Укажите основание премии');state.status='APPROVED';state.approvedAt=new Date().toISOString();repo.save(state);render()};$('#export-btn').onclick=()=>downloadXlsx(buildWorkbookData({...state,guards:demoData.guards,rates:{mode:'SHIFT',amount:state.rateAmount,version:demoData.rates.version}}),`Расчет-ЗП-${state.month}.xlsx`);$('#reset-btn').onclick=()=>{repo.reset(state.month);load()};load();
