import {demoData} from './data.mjs';import {LocalScheduleRepository} from './repository.mjs';import {daysInMonth,calculateGuardPayroll,assessWorkload,canEditSchedule} from './domain.mjs';import {buildWorkbookData,downloadXlsx} from './export.mjs';
const $=s=>document.querySelector(s), repo=new LocalScheduleRepository();let selected='g1',hours=12,state;
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function newState(){return{month:$('#month').value,status:'DRAFT',assignments:[],bonuses:{}}}function load(){state=repo.load($('#month').value)||newState();render()}
function fillSelect(el,items){el.innerHTML=items.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
function object(){return demoData.legalEntities.find(x=>x.id===$('#legal').value).objects.find(x=>x.id===$('#object').value)}
function syncFilters(){const le=demoData.legalEntities.find(x=>x.id===$('#legal').value);fillSelect($('#object'),le.objects);syncObject()}
function syncObject(){const o=object();fillSelect($('#post'),o.posts);$('#inspection').textContent=o.inspection;renderGrid()}
function renderGuards(){const q=$('#guard-search').value.toLowerCase();$('#guards').innerHTML=demoData.guards.filter(g=>g.name.toLowerCase().includes(q)).map(g=>`<div class="guard ${g.id===selected?'active':''}" draggable="true" data-id="${g.id}" title="Перетащите на день графика"><b>${g.name}</b><small>${g.engagement} · ${g.rank}</small></div>`).join('');document.querySelectorAll('.guard').forEach(x=>{x.onclick=()=>{selected=x.dataset.id;render()};x.ondragstart=e=>{selected=x.dataset.id;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',x.dataset.id)}})}
function renderGrid(){if(!state)return;const [y,m]=state.month.split('-').map(Number),days=daysInMonth(y,m);$('#schedule-grid').style.setProperty('--days',days);let h='<div class="cell head name">Сотрудник</div>';for(let d=1;d<=days;d++)h+=`<div class="cell head">${d}</div>`;for(const g of demoData.guards){h+=`<div class="cell name">${g.name.split(' ').slice(0,2).join(' ')}</div>`;for(let d=1;d<=days;d++){const a=state.assignments.find(x=>x.guardId===g.id&&x.day===d),cl=a?.hours===0?'vacation':a?'filled':'';h+=`<div class="cell slot ${cl}" data-g="${g.id}" data-d="${d}">${a?a.hours===0?'ОТП':a.hours:''}</div>`}}$('#schedule-grid').innerHTML=h;document.querySelectorAll('.slot').forEach(c=>{c.onclick=()=>toggle(c.dataset.g,Number(c.dataset.d));c.ondragover=e=>{e.preventDefault();c.classList.add('dragover')};c.ondragleave=()=>c.classList.remove('dragover');c.ondrop=e=>{e.preventDefault();c.classList.remove('dragover');const guardId=e.dataTransfer.getData('text/plain');assign(guardId,Number(c.dataset.d))}})}
function assign(g,d){if(!g||!canEditSchedule(state))return;const i=state.assignments.findIndex(x=>x.guardId===g&&x.day===d);if(i>=0)state.assignments.splice(i,1);const current=state.assignments.filter(x=>x.guardId===g);if(assessWorkload([...current,{hours}]).level==='HIGH'&&!confirm('Риск усталости: высокая нагрузка. Подтвердить назначение?'))return;state.assignments.push({guardId:g,day:d,hours,post:$('#post').selectedOptions[0].text});selected=g;repo.save(state);render()}
function toggle(g,d){if(!canEditSchedule(state))return;const i=state.assignments.findIndex(x=>x.guardId===g&&x.day===d);if(i>=0)state.assignments.splice(i,1);else{const current=state.assignments.filter(x=>x.guardId===g);if(assessWorkload([...current,{hours}]).level==='HIGH'&&!confirm('Риск усталости: высокая нагрузка. Подтвердить назначение?'))return;state.assignments.push({guardId:g,day:d,hours,post:$('#post').selectedOptions[0].text})}repo.save(state);render()}
function renderCard(){const g=demoData.guards.find(x=>x.id===selected),items=state.assignments.filter(x=>x.guardId===selected),risk=assessWorkload(items),b=state.bonuses[selected]||{amount:0,reason:''},p=calculateGuardPayroll(items,demoData.rates,b.amount);$('#guard-card').innerHTML=`<div><span class="eyebrow">КАРТОЧКА ОХРАННИКА</span><h2>${g.name}</h2><div>${g.note}</div></div><div class="metric">Статус<b>${g.status}</b><br>${g.engagement}</div><div class="metric">Допуски<b>${g.rank}</b><br>УЛЧО: ${g.license}</div><div class="metric">Контакты<b>${g.phone}</b><br>Стаж: ${g.experience}</div><div class="metric">Назначение<b>${object().name}</b><br>${$('#post').selectedOptions[0].text}</div>`;$('#risk-box').className=risk.level==='HIGH'?'risk-high':'risk-ok';$('#risk-box').innerHTML=`<b>${risk.level==='OK'?'Нагрузка в норме':'Требует внимания'}</b><br>${risk.hours} ч · ${risk.reasons.join(', ')||'критических рисков нет'}`;$('#pay-box').textContent=`${p.hours} ч · ${p.shifts} смен · ${money(p.total)}`;$('#bonus').value=b.amount;$('#bonus-reason').value=b.reason;$('#schedule-title').textContent=`${object().name} · ${state.month}`;$('#status-badge').textContent=state.status==='APPROVED'?'Утверждён':'Черновик';$('#approve-btn').disabled=!canEditSchedule(state);$('#export-btn').disabled=state.status!=='APPROVED'}
function render(){renderGuards();renderGrid();renderCard()}
$('#login-btn').onclick=()=>{if($('#password').value==='KIRASA'){$('#login').hidden=true;$('#app').hidden=false}else $('#login-error').textContent='Неверный пароль'};fillSelect($('#legal'),demoData.legalEntities);fillSelect($('#template'),demoData.templates);syncFilters();$('#legal').onchange=syncFilters;$('#object').onchange=syncObject;$('#post').onchange=render;$('#month').onchange=load;$('#guard-search').oninput=renderGuards;document.querySelectorAll('.shift').forEach(b=>b.onclick=()=>{document.querySelectorAll('.shift').forEach(x=>x.classList.remove('active'));b.classList.add('active');hours=Number(b.dataset.hours)});$('#bonus').oninput=$('#bonus-reason').oninput=()=>{const amount=Number($('#bonus').value)||0,reason=$('#bonus-reason').value;if(amount&&!reason)return;state.bonuses[selected]={amount,reason};repo.save(state);renderCard()};$('#approve-btn').onclick=()=>{if(Object.values(state.bonuses).some(x=>x.amount&&!x.reason))return alert('Укажите основание премии');state.status='APPROVED';state.approvedAt=new Date().toISOString();repo.save(state);render()};$('#export-btn').onclick=()=>downloadXlsx(buildWorkbookData({...state,guards:demoData.guards,rates:demoData.rates}),`Расчет-ЗП-${state.month}.xlsx`);$('#reset-btn').onclick=()=>{repo.reset(state.month);load()};load();
